global:
  scrape_interval: 5s # How often to check for data

scrape_configs:
  # 1. Monitor the Python App
  - job_name: 'python-app'
    static_configs:
      - targets: ['python-app:5000']

  # 2. Monitor the Server (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
