server {
    listen 80;

    location / {
        proxy_pass http://python-app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /socket.io/ {
        proxy_pass http://python-app:5000/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # Optional: ensure /metrics is accessible via the proxy if needed
    location /metrics {
        proxy_pass http://python-app:5000/metrics;
    }
}
